apiVersion: v1
kind : ConfigMap
metadata:
  name: first-configmap
  labels:
     app: myapp
data:
  NODE_ENV=PRODUCTION
  PORT=7100
---

apiVersion: apps/v1
kind : Deployment
metadata:
  name: first-deployment
  namespace: kubernetes-cluster-manishkumar19
  labels:
     app: myapp
  annotations:
    kubernetes.io/change-cause: "My custom message 2"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: first-replicaset
      labels:
        app: myapp
    spec:
      containers:
        - image: manishsurbo/i-manishkumar19-master:latest
          name: first-app
          ports:
            - containerPort: 7100
#          envFrom:
#            - configMapRef:
#              name: app-settings
  replicas: 4
  selector:
    matchLabels:
      app: myapp

---
apiVersion: v1
kind: Service
metadata:
  name: first-node-port-service
  namespace: kubernetes-cluster-manishkumar19
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 7100  # service port
      nodePort: 30008
  selector:
    app: myapp




